/**
 * Server-side helper for the `/inference/agentic` telemetry catalog.
 *
 * Turns the raw per-config rows from `getAgenticCatalog` into the
 * model-grouped, label-resolved shape the page renders. Mirrors how
 * `compare-availability.ts` feeds the `/compare` index: a cached DB read on
 * the server, a fixture in e2e mode, and all presentation mapping done here
 * rather than in the query.
 *
 * Rows whose model or hardware key is unknown to the registries are dropped —
 * a config we cannot label is a card the reader cannot act on, and the
 * catalog is navigation, not a data export.
 */

import { FIXTURES_MODE, getDb } from '@semianalysisai/inferencex-db/connection';

import {
  type AgenticCatalogEntry,
  getAgenticCatalog,
} from '@semianalysisai/inferencex-db/queries/agentic-catalog';

import { FRAMEWORK_LABELS, HW_REGISTRY } from '@semianalysisai/inferencex-constants';

import { cachedQuery } from '@/lib/api-cache';
import { COMPARE_MODEL_SLUGS } from '@/lib/compare-slug';
import { loadFixture } from '@/lib/test-fixtures';

/**
 * The fixture is regenerated by hand rather than by `capture:fixtures`: the
 * catalog has no public API route to fetch, so there is nothing for the
 * capture script to hit. 47 rows of pure metadata, so it stays cheap to refresh.
 */
export const getCachedAgenticCatalog = cachedQuery(() => {
  if (FIXTURES_MODE) return Promise.resolve(loadFixture<AgenticCatalogEntry[]>('agentic-catalog'));

  return getAgenticCatalog(getDb());
}, 'agentic-catalog');

export interface AgenticCatalogCard {
  /** `/inference/agentic/<id>` — the representative point for this config. */
  id: number;
  /** "B200 · vLLM" — what the card leads with. */
  label: string;
  hardwareKey: string;
  hardwareLabel: string;
  frameworkLabel: string;
  precisionLabel: string;
  vendor: string;
  arch: string;
  points: number;
  minConc: number;
  maxConc: number;
  latestDate: string;
}

export interface AgenticCatalogModelGroup {
  /** DB model key, used as the section anchor. */
  key: string;
  /** "Kimi K3 2.8T" — the same label the AgentX ledger shows. */
  label: string;
  cards: AgenticCatalogCard[];
  /** Trace-backed points across every config in this model. */
  totalPoints: number;
}

/** DB model key → the compare catalog's display label, so the telemetry
 *  catalog and the AgentX ledger name the same model the same way. */
function buildModelLabels(): Map<string, string> {
  const labels = new Map<string, string>();
  for (const model of COMPARE_MODEL_SLUGS) {
    for (const dbKey of model.dbKeys) labels.set(dbKey, model.label);
  }
  return labels;
}

/** Precision keys are short and uppercase in the UI ("fp4" → "FP4"). */
function precisionLabel(precision: string): string {
  return precision.toUpperCase();
}

export function groupAgenticCatalog(rows: AgenticCatalogEntry[]): AgenticCatalogModelGroup[] {
  const modelLabels = buildModelLabels();
  const groups = new Map<string, AgenticCatalogModelGroup>();

  for (const row of rows) {
    const modelLabel = modelLabels.get(row.model);
    const hw = HW_REGISTRY[row.hardware];
    if (!modelLabel || !hw) continue;

    const frameworkLabel = FRAMEWORK_LABELS[row.framework] ?? row.framework;
    const group = groups.get(row.model) ?? {
      key: row.model,
      label: modelLabel,
      cards: [],
      totalPoints: 0,
    };
    group.cards.push({
      id: row.id,
      label: `${hw.label} · ${frameworkLabel}`,
      hardwareKey: row.hardware,
      hardwareLabel: hw.label,
      frameworkLabel,
      precisionLabel: precisionLabel(row.precision),
      vendor: hw.vendor,
      arch: hw.arch,
      points: row.points,
      minConc: row.minConc,
      maxConc: row.maxConc,
      latestDate: row.latestDate,
    });
    group.totalPoints += row.points;
    groups.set(row.model, group);
  }

  const ordered = [...groups.values()];
  // Cards follow the chart's hardware sort order so a reader scanning the
  // catalog meets SKUs in the same sequence the legend uses.
  for (const group of ordered) {
    group.cards.sort(
      (a, b) =>
        (HW_REGISTRY[a.hardwareKey]?.sort ?? 0) - (HW_REGISTRY[b.hardwareKey]?.sort ?? 0) ||
        a.label.localeCompare(b.label),
    );
  }
  // Models with the most telemetry lead, so the richest sections are on top.
  ordered.sort((a, b) => b.totalPoints - a.totalPoints || a.label.localeCompare(b.label));
  return ordered;
}

export async function getAgenticCatalogGroups(): Promise<AgenticCatalogModelGroup[]> {
  return groupAgenticCatalog(await getCachedAgenticCatalog());
}
