import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * The blog post pages import `katex/dist/katex.min.css` from the top-level `katex`
 * dependency, but the HTML those styles have to match is generated by whatever `katex`
 * copy `rehype-katex` resolves. If the two drift apart the math still renders — it just
 * renders unstyled, because KaTeX renames layout classes across majors (0.16 emits
 * `.base` / `.strut`; 0.18 renamed them to `.katex-base` / `.katex-strut`).
 *
 * Bumping `katex` past what `rehype-katex` supports must fail here, not in review.
 */

const appRequire = createRequire(import.meta.url);
const rendererRequire = createRequire(appRequire.resolve('rehype-katex'));

const katexVersion = (require_: NodeJS.Require) =>
  (require_('katex/package.json') as { version: string }).version;

describe('KaTeX CSS matches the KaTeX that renders the HTML', () => {
  it('resolves the same katex version for the stylesheet and the renderer', () => {
    expect(katexVersion(rendererRequire)).toBe(katexVersion(appRequire));
  });

  it('styles the layout classes the renderer actually emits', async () => {
    const katexModule = await import('katex');
    const katex = katexModule.default;
    const html = katex.renderToString('x^2', { throwOnError: false });

    const cssPath = path.join(
      path.dirname(appRequire.resolve('katex/package.json')),
      'dist',
      'katex.min.css',
    );
    const css = fs.readFileSync(cssPath, 'utf8');

    const emitted = new Set(
      [...html.matchAll(/class="(?<names>[^"]+)"/gu)].flatMap((m) => m.groups!.names.split(/\s+/u)),
    );
    expect(emitted).toContain('katex');

    // `base` and `strut` are the classes that silently changed name in 0.18. Asserting
    // the renderer still emits them is the other half of the guard: if a future version
    // renames them, the CSS check below would pass vacuously.
    for (const cls of ['base', 'strut']) {
      expect([...emitted], `expected the renderer to emit .${cls}`).toContain(cls);
      expect(css, `renderer emits .${cls} but the CSS never styles it`).toContain(`.${cls}`);
    }
  });
});
