name: Zizmor

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, ready_for_review]
    paths:
      - '.github/dependabot.yml'
      - '.github/zizmor.yml'
      - '.github/workflows/**'
      - '.github/actions/**'
      - 'action.yml'
      - 'action.yaml'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Audit GitHub Actions
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Audit workflows
        run: uvx --exclude-newer P1D zizmor@latest --strict-collection --pedantic
          --no-ignores .
